version: '3'

services: 
  selenium:
    container_name: selenium
    environment: 
      - START_XFVB=false
    image: selenium/standalone-firefox
  
  linkscraping:
    build: .
    ports: 
      - '8000:8000'
    volumes: 
      - .:/usr/local/src/linkscraping
    command: >
      sh -c 'python link_scraping/manage.py runserver 0.0.0.0:8000'
      