version: '3'

services: 
  linkscraping:
    build: .
    ports: 
      - '8000:8000'
    volumes: 
      - .:/usr/local/src/linkscraping
    command: >
      sh -c 'python manage.py runserver 0.0.0.0:8000'
      