# Generated by Django 3.0.5 on 2020-09-17 21:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ParentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GrandChildLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('parent_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.ChildLink')),
            ],
        ),
        migrations.AddField(
            model_name='childlink',
            name='parent_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.ParentLink'),
        ),
    ]
