# Generated by Django 3.0.5 on 2020-09-17 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='childlink',
            name='link_title',
        ),
        migrations.AlterField(
            model_name='childlink',
            name='url',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='GrandChildLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('parent_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.ChildLink')),
            ],
        ),
        migrations.AlterField(
            model_name='childlink',
            name='parent_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.ParentLink'),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
